import "./globals.css";
import { Suspense } from "react";
import { Montserrat, Oswald } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import AuthStatus from "@/components/auth-status";
import { ThemeProvider } from "@/components/theme-provider";

const fontSans = Montserrat({
  subsets: ["latin"],
  variable: "--font-sans",
});
const fontHeading = Oswald({
  subsets: ["latin"],
  variable: "--font-heading",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "font-sans antialiased",
          fontSans.variable,
          fontHeading.variable,
          "bg-white dark:bg-[#313338] min-h-[100dvh]"
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem={false}
          disableTransitionOnChange
        >
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
